/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Wed, Feb 05, 2020                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :H8/36064                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
#pragma stacksize 0x100         /* Do not modify this line. */
